Repository tachiyomiorg/website, pull requests merged in 2019-09, with the labels that each got.

#9 Rewrite website using VuePress
  .gitignore
  README.md
  package-lock.json
  package.json
  src/.vuepress/components/ExtensionList.vue
  src/.vuepress/config.js
  src/.vuepress/enhanceApp.js
  src/.vuepress/public/CNAME
  src/.vuepress/public/assets/media/addtolibrary.mp4
  src/.vuepress/public/assets/media/addtolibrary.png
  src/.vuepress/public/assets/media/addtolibrary.webm
  src/.vuepress/public/assets/media/extensioninstaller.mp4
  src/.vuepress/public/assets/media/extensioninstaller.png
  src/.vuepress/public/assets/media/extensioninstaller.webm
  src/.vuepress/public/assets/media/hero.png
  src/.vuepress/public/assets/media/installprompt.png
  src/.vuepress/public/assets/media/screens.png
  src/.vuepress/public/assets/media/tachiyomi.png
  src/.vuepress/public/assets/media/unknownapps-api25.mp4
  src/.vuepress/public/assets/media/unknownapps-api25.png
  src/.vuepress/public/assets/media/unknownapps-api25.webm
  src/.vuepress/public/assets/media/unknownapps-api28.mp4
  src/.vuepress/public/assets/media/unknownapps-api28.png
  src/.vuepress/public/assets/media/unknownapps-api28.webm
  src/.vuepress/public/favicon.ico
  src/.vuepress/styles/index.scss
  src/.vuepress/styles/palette.styl
  src/README.md
  src/assets/css/bootstrap-4.3.1.min.css
  src/assets/css/bootstrap-4.3.1.min.css.map
  src/assets/css/bootstrap-toc-1.0.1.min.css
  src/assets/css/style.css
  src/assets/js/bootstrap-4.3.1.min.js
  src/assets/js/bootstrap-4.3.1.min.js.map
  src/assets/js/bootstrap-toc-1.0.1.min.js
  src/assets/js/jquery-3.4.1.slim.min.js
  src/assets/js/jquery-3.4.1.slim.min.map
  src/assets/js/script.js
  src/extensions/README.md
  src/faq/README.md
  src/guide/README.md
  src/index.html
Labels: Priority: Medium, Status: In Progress, Type: Discussion, Type: Enhancement

#16 Update front page sample images
  src/.vuepress/public/assets/media/screens.png
Labels: Priority: Low, Status: Available, Type: Enhancement

#17 Add FAQ spoilers and fixed a typo.
  package-lock.json
  package.json
  src/.vuepress/config.js
  src/help/faq/extensions/README.md
Labels: Priority: Low, Status: Available, Type: Enhancement

#21 Fixed sidebar navigation for FAQ
  src/.vuepress/config.js
  src/help/faq/README.md
  src/help/faq/application.md
  src/help/faq/extensions.md
Labels: Enhancement

#22 Enhanced FAQ
  src/.vuepress/config.js
  src/help/faq/application.md
  src/help/faq/extensions.md
  src/help/guides/getting-started.md
  src/help/guides/reading-local-manga.md
  src/help/guides/source-problems.md
  src/help/guides/translation.md
Labels: Enhancement

#30 Move navigation and plugins away from config.js (Split 1 of 3 - #27)
  src/.vuepress/config.js
  src/.vuepress/config/nav.js
  src/.vuepress/config/plugins.js
  src/.vuepress/config/sidebar.js
  src/help/guides/translation.md
Labels: Enhancement, Workflow

#34 Added descriptions to all options under downloads
  src/help/guides/downloads.md
Labels: Enhancement

#36 Add clean URLs to the site
  package-lock.json
  package.json
  src/.vuepress/config/plugins.js
Labels: Enhancement, Feature

#42 Trailing hotfix for #36
  package-lock.json
  package.json
  src/.vuepress/config/plugins.js
Labels: Critical Priority
