Repository tachiyomiorg/website, pull requests merged in 2020-05, with the labels that each got.

#153 [0.9.0] Rework Getting started
  src/.vuepress/components/DownloadButtons.vue
  src/.vuepress/components/Navigation.vue
  src/.vuepress/components/VersionTag.vue
  src/help/faq/README.md
  src/help/guides/creating-backups.md
  src/help/guides/getting-started.md
  src/help/guides/source-problems.md
Labels: High Priority

#157 [0.9.0] Replace screenshots on homepage
  src/.vuepress/public/assets/media/browse.png
  src/.vuepress/public/assets/media/catalogues.png
  src/.vuepress/public/assets/media/manga.png
  src/.vuepress/public/assets/media/my-library.png
  src/README.md
Labels: High Priority

#155 Updating for J2K MD2
  src/.vuepress/public/assets/media/fork-J2K-banner.gif
  src/.vuepress/public/assets/media/fork-J2K-banner.jpg
  src/.vuepress/public/assets/media/fork-J2K-banner.png
  src/forks/TachiyomiJ2K.md
Labels: High Priority

#158 Update Neko for MD2 release
  src/.vuepress/components/ForkButtons.vue
  src/.vuepress/public/assets/media/fork-Neko-banner.png
  src/.vuepress/public/assets/media/fork-Neko-icon.png
  src/forks/Neko.md
  src/forks/TachiyomiAZ.md
  src/forks/TachiyomiEH.md
  src/forks/TachiyomiJ2K.md
Labels: High Priority

#174 Hotfix mobile dropdown
  src/.vuepress/styles/index.styl
Labels: Critical Priority

#176 Add descriptions to all pages
  src/extensions/README.md
  src/forks/README.md
  src/help/README.md
  src/help/contribution.md
  src/help/faq/README.md
  src/help/guides/categories.md
  src/help/guides/creating-backups.md
  src/help/guides/getting-started.md
  src/help/guides/reading-local-manga.md
  src/help/guides/settings/README.md
  src/help/guides/settings/advanced.md
  src/help/guides/settings/backup.md
  src/help/guides/settings/downloads.md
  src/help/guides/settings/general.md
  src/help/guides/settings/reader.md
  src/help/guides/settings/tracking.md
  src/help/guides/source-migration.md
  src/help/guides/source-problems.md
Labels: Help Wanted

#200 Quickfix sidebar not showing on help
  src/.vuepress/components/Help.vue
Labels: High Priority

#211 Fix duplicate key on Navigation.vue
  src/.vuepress/components/Navigation.vue
Labels: High Priority
